### ISSUE TITLE
The uservoice tag ovelaps the title

### ISSUE THREAD

**Issue by davidascher** [mozilla/mozilla-ignite#49]
that's just ugly =)

**Comment by rossbruniges** [comment]
It also won't be making it to live :)

It was a failed attempt to try and obtain user feedback :(

Thanks for pointing it out though - as I keep on telling people, I am no designer!

**Comment by rossbruniges** [comment]
Uservoice has been deleted. It was a nice experiment, and one that showed uservoice to not actually be very useful.
